# Generated by Django 4.0.10 on 2024-07-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_initial'),
        ('learning', '0001_initial'),
        ('hackathons', '0001_initial'),
        ('forums', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.language'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='prizes_details',
            field=models.ManyToManyField(to='hackathons.hackathonprizedetails'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='round_details',
            field=models.ManyToManyField(to='hackathons.hackathonrounddetails'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='skills',
            field=models.ManyToManyField(blank=True, to='learning.skill'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='user_group',
            field=models.ManyToManyField(blank=True, to='access.institutionusergroupdetail'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='zone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forums.zone'),
        ),
    ]
