FROM python:3.11.1-slim-buster

# Initial update & initial dependencies
RUN apt-get update && apt-get install -y supervisor gcc g++ python3-dev curl gnupg

# curl the source list for MSSQL & Drivers from microsoft
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update

# PyODBC & MS SQL Driver dependencies
RUN ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

# cleaning up unused files
RUN apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -rf /var/lib/apt/lists/*

# Install requirements
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# supervisor conf & related files
COPY ./docker/deployment/conf/supervisord.conf /etc/supervisor/supervisord.conf

# Custom working directory
WORKDIR /app

# NOTE: One file is enough for both backend & supervisor, no big change.
