# flake8: noqa
from .home import (
    MyCourseLearningsHomeAPIView, 
    MyLearningsCertificateDownloadAPIView, 
    MyLearningsCertificateListAPIView, 
    MyLearningsNotesAPIView, 
    MyLearningsNotesListAPIView, 
    MyLearningPathHomeAPIView, 
    MyCertificatePathHomeAPIView,
    MySubscriptionPlanHomeAPIView, 
    MyLearningRoleHomeAPIView,
    StudentEnrolledCourseTracker, 
    StudentMyCourseLearningsHomeAPIView, 
    MySubModulesVideoBookMarkAPIView, 
    EntityAddToBookMarkAPIView,
    MySkillHomeAPIView,
    StudentMyLearningPathHomeAPIView,
    StudentMyCertificatePathHomeAPIView,
    MyLearningsOverallNotesListAPIView,
    MyLearningsNotesFilterMetaAPIView,
    CourseRatingAPIView,
    LearningContentFeedbackAPIView,
    CourseCompletedPageAPIView,
    MyBlendedLearningPathHomeAPIView,
    MyJobEligibleSkillHomeAPIView,
    MyMMLCourseLearningsHomeAPIView,
)
from .learn import (
    UserLearningTrackerStartAPIView, 
    UserVisitedCourseSubModuleTrackerAPIView, 
    UserVisitedCourseModuleTrackerAPIView,
    UserVisitedLearningPathCourseTrackerAPIView, 
    UserVisitedLearningPathCourseModuleTrackerAPIView, 
    UserVisitedLearningPathCourseSubModuleTrackerAPIView, 
    UserVisitedCertificatePathLearningPathCourseTrackerAPIView, 
    UserVisitedCertificatePathLearningPathTrackerAPIView, 
    UserVisitedCertificatePathLearningPathCourseModuleTrackerAPIView, 
    UserVisitedCertificatePathLearningPathCourseSubModuleTrackerAPIView, 
    StudentVisitedCourseSubModuleTrackerAPIView, 
    StudentVisitedCourseModuleTrackerAPIView, 
    StudentLearningTrackerStartAPIView, 
    UserLearningPathTrackerStartAPIView, 
    UserCertificatePathTrackerStartAPIView,
    SubscriptionLearningTrackerStartAPIView,
    UserMMLCourseLearningTrackerStartAPIView,

    SubscriptionVisitedCourseModuleTrackerAPIView,
    SubscriptionVisitedCourseSubModuleTrackerAPIView,
    SubscriptionVisitedLearningPathCourseTrackerAPIView,
    SubscriptionVisitedLearningPathCourseModuleTrackerAPIView,
    SubscriptionVisitedLearningPathCourseSubModuleTrackerAPIView,

    SubscriptionVisitedCertificatePathLearningPathTrackerAPIView,
    SubscriptionVisitedCertificatePathLearningPathCourseTrackerAPIView,
    SubscriptionVisitedCertificatePathLearningPathCourseModuleTrackerAPIView,
    SubscriptionVisitedCertificatePathLearningPathCourseSubModuleTrackerAPIView,

    StudentLearningPathTrackerStartAPIView,
    StudentCertificatePathTrackerStartAPIView,
    LearningRoleStartAPIView,
    SkillStartAPIView,
    UserBlendedLearningPathTrackerStartAPIView,
    UserVisitedBlendedLearningPathCourseTrackerAPIView,
    UserVisitedBlendedLearningPathCourseModuleTrackerAPIView,
    UserVisitedBlendedLearningPathCourseSubModuleTrackerAPIView,
    UserBlendedLearningPathTrackerDetailsAPIView,

    SkillVisitedCourseModuleTrackerAPIView,
    SkillVisitedCourseSubModuleTrackerAPIView,
    SkillVisitedLearningPathCourseTrackerAPIView,
    SkillVisitedLearningPathCourseModuleTrackerAPIView,
    SkillVisitedLearningPathCourseSubModuleTrackerAPIView,
    SkillVisitedCertificatePathLearningPathTrackerAPIView,
    SkillVisitedCertificatePathLearningPathCourseTrackerAPIView,
    SkillVisitedCertificatePathLearningPathCourseModuleTrackerAPIView,
    SkillVisitedCertificatePathLearningPathCourseSubModuleTrackerAPIView,

    JobEligibleSkillLearningTrackerStartAPIView,
    JobEligibleSkillVisitedCourseModuleTrackerAPIView,
    JobEligibleSkillVisitedCourseSubModuleTrackerAPIView,
    JobEligibleSkillVisitedLearningPathCourseTrackerAPIView,
    JobEligibleSkillVisitedLearningPathCourseModuleTrackerAPIView,
    JobEligibleSkillVisitedLearningPathCourseSubModuleTrackerAPIView,

    JobEligibleSkillVisitedCertificatePathLearningPathTrackerAPIView,
    JobEligibleSkillVisitedCertificatePathLearningPathCourseTrackerAPIView,
    JobEligibleSkillVisitedCertificatePathLearningPathCourseModuleTrackerAPIView,
    JobEligibleSkillVisitedCertificatePathLearningPathCourseSubModuleTrackerAPIView,
    UserVisitedMMLCourseTrackerAPIView,

    StudentVisitedLearningPathCourseTrackerAPIView,
    StudentVisitedLearningPathCourseModuleTrackerAPIView,
    StudentVisitedLearningPathCourseSubModuleTrackerAPIView,
)
