# Generated by Django 4.0.10 on 2024-07-09 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0001_initial'),
        ('learning', '0001_initial'),
        ('meta', '0001_initial'),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionusergroupcontent',
            name='certification_path',
            field=models.ManyToManyField(blank=True, to='learning.certificationpath'),
        ),
        migrations.AddField(
            model_name='institutionusergroupcontent',
            name='courses',
            field=models.ManyToManyField(blank=True, to='learning.course'),
        ),
        migrations.AddField(
            model_name='institutionusergroupcontent',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionusergroupcontent',
            name='learning_path',
            field=models.ManyToManyField(blank=True, to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='institutionusergroupcontent',
            name='user_group',
            field=models.ManyToManyField(blank=True, to='access.institutionusergroupdetail'),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='accreditation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.accreditation'),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='banner_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.institutionbannerimage'),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='certification_paths',
            field=models.ManyToManyField(blank=True, to='learning.certificationpath'),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.city'),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.country'),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='courses',
            field=models.ManyToManyField(blank=True, to='learning.course'),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='learning_paths',
            field=models.ManyToManyField(blank=True, to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='representative',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutiondetail',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.state'),
        ),
        migrations.AddField(
            model_name='institutionbannerimage',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerlogoimage',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerdetail',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.city'),
        ),
        migrations.AddField(
            model_name='employerdetail',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.country'),
        ),
        migrations.AddField(
            model_name='employerdetail',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerdetail',
            name='logo_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.employerlogoimage'),
        ),
        migrations.AddField(
            model_name='employerdetail',
            name='representative',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerdetail',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.state'),
        ),
        migrations.AddField(
            model_name='user',
            name='career_highlights',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.careerhighlights'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.employerdetail'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='education_details',
            field=models.ManyToManyField(blank=True, to='meta.educationdetail'),
        ),
        migrations.AddField(
            model_name='user',
            name='font_style',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.fontstyle'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.usergender'),
        ),
        migrations.AddField(
            model_name='user',
            name='identification_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.useridentificationtype'),
        ),
        migrations.AddField(
            model_name='user',
            name='industry_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathons.industrytype'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_details',
            field=models.ManyToManyField(blank=True, to='meta.userjobdetail'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_area_of_interests',
            field=models.ManyToManyField(blank=True, to='learning.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_highest_education',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.onboardinghighesteducation'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.onboardinglevel'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.userprofileimage'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.userprofileresume'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_handles',
            field=models.ManyToManyField(to='meta.usersocialmediahandle'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.state'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.userrole'),
        ),
    ]
